import { realpathSync } from 'node:fs';
import { mkdir, readFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GauntletConfig, GeneratedManifest, TestPlan } from './types.js';
import { atomicWrite, ensureWithin, sha256, stableStringify } from './utils.js';

const RENDERER_VERSION = '1.0.0';

function testSource(generatedDir: string): string {
  const runtimePath = realpathSync(fileURLToPath(new URL('./generated-runtime.js', import.meta.url)));
  const canonicalGeneratedDir = realpathSync(generatedDir);
  let relativeRuntime = path.relative(canonicalGeneratedDir, runtimePath).replaceAll(path.sep, '/');
  if (!relativeRuntime.startsWith('.')) relativeRuntime = `./${relativeRuntime}`;
  return `/* Auto-generated by Playwright API Gauntlet. Do not hand-edit. */
import { executeIsolated, executeGeneratedCase, executeGeneratedWorkflow, loadGeneratedPlan, test } from '${relativeRuntime}';

const plan = loadGeneratedPlan(import.meta.url);

test.describe.configure({ mode: 'default' });

for (const planned of plan.cases) {
  test(\`[\${planned.id}] \${planned.title}\`, async ({ request }, testInfo) => {
    await executeIsolated(request, testInfo, plan, () => executeGeneratedCase(request, testInfo, planned), planned);
  });
}

for (const workflow of plan.workflows) {
  test(\`[workflow:\${workflow.id}] \${workflow.title}\`, async ({ request }, testInfo) => {
    await executeIsolated(request, testInfo, plan, () => executeGeneratedWorkflow(request, testInfo, workflow), workflow);
  });
}
`;
}

export async function generateArtifacts(plan: TestPlan, config: GauntletConfig): Promise<GeneratedManifest> {
  const generatedDir = ensureWithin(path.dirname(config.generatedDir), config.generatedDir);
  await mkdir(generatedDir, { recursive: true });
  const planPath = ensureWithin(generatedDir, path.join(generatedDir, 'plan.generated.json'));
  const testPath = ensureWithin(generatedDir, path.join(generatedDir, 'api.generated.spec.mjs'));
  const planContents = stableStringify(plan);
  const testContents = testSource(generatedDir);
  await unlink(path.join(generatedDir, 'api.generated.spec.ts')).catch(() => undefined);
  await atomicWrite(planPath, planContents);
  await atomicWrite(testPath, testContents);
  const files = {
    'plan.generated.json': sha256(planContents),
    'api.generated.spec.mjs': sha256(testContents),
  };
  const manifest: GeneratedManifest = {
    formatVersion: 1,
    rendererVersion: RENDERER_VERSION,
    projectName: plan.projectName,
    specPath: plan.specPath,
    specHash: plan.specHash,
    seed: plan.seed,
    planHash: sha256(planContents),
    caseCount: plan.cases.length,
    workflowCount: plan.workflows.length,
    operationCount: plan.operations.length,
    ...(plan.discovery ? { discoveryHash: plan.discovery.discoveryHash } : {}),
    files,
  };
  await atomicWrite(path.join(generatedDir, 'manifest.json'), stableStringify(manifest));
  return manifest;
}

export async function verifyGeneratedArtifacts(config: GauntletConfig): Promise<{ valid: boolean; mismatches: string[]; manifest: GeneratedManifest }> {
  const manifestPath = path.join(config.generatedDir, 'manifest.json');
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as GeneratedManifest;
  const mismatches: string[] = [];
  for (const [relative, expectedHash] of Object.entries(manifest.files)) {
    const filePath = ensureWithin(config.generatedDir, path.join(config.generatedDir, relative));
    try {
      const actual = sha256(await readFile(filePath));
      if (actual !== expectedHash) mismatches.push(`${relative}: expected ${expectedHash}, got ${actual}`);
    } catch {
      mismatches.push(`${relative}: missing`);
    }
  }
  return { valid: mismatches.length === 0, mismatches, manifest };
}
